<a href="https://colab.research.google.com/github/itimes-digital/Bootcamp-Analista-de-Machine-Learning-IGTI/blob/master/desafio_modelo_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('winequality-red.csv', sep=';')
dataset.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [4]:
dataset.shape

(1599, 12)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [6]:
dataset.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [7]:
dataset['residual sugar'].isnull().sum()

0

In [8]:
dataset.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [9]:
dataset['residual sugar'].median()

2.2

In [10]:
dataset[['fixed acidity', 'pH']].corr()

fixed acidity        pH
fixed acidity       1.000000 -0.682978
pH                 -0.682978  1.000000

In [11]:
dataset[['quality', 'alcohol']].corr()

quality   alcohol
quality  1.000000  0.476166
alcohol  0.476166  1.000000

In [15]:
dataset.query('quality == 5').count()

fixed acidity           681
volatile acidity        681
citric acid             681
residual sugar          681
chlorides               681
free sulfur dioxide     681
total sulfur dioxide    681
density                 681
pH                      681
sulphates               681
alcohol                 681
quality                 681
dtype: int64

In [32]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(dataset)
print(scaler)

MinMaxScaler(copy=True, feature_range=(0, 1))


In [33]:
previsores = dataset.iloc[:, 0]

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]


In [34]:
print(scaler.data_min_)

[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]


In [41]:
scaler = MinMaxScaler()

In [40]:
previsores = np.hsplit(dataset_scaler, np.array([0, 11]))
previsores

[array([], shape=(1599, 0), dtype=float64),
 array([[0.24778761, 0.39726027, 0.        , ..., 0.60629921, 0.13772455,
         0.15384615],
        [0.28318584, 0.52054795, 0.        , ..., 0.36220472, 0.20958084,
         0.21538462],
        [0.28318584, 0.43835616, 0.04      , ..., 0.40944882, 0.19161677,
         0.21538462],
        ...,
        [0.15044248, 0.26712329, 0.13      , ..., 0.53543307, 0.25149701,
         0.4       ],
        [0.11504425, 0.35958904, 0.12      , ..., 0.65354331, 0.22754491,
         0.27692308],
        [0.12389381, 0.13013699, 0.47      , ..., 0.51181102, 0.19760479,
         0.4       ]]),
 array([[0.4],
        [0.4],
        [0.4],
        ...,
        [0.6],
        [0.4],
        [0.6]])]

In [25]:
previsores

array([[ 0.7  ,  0.   ,  1.9  , ...,  0.56 ,  9.4  ,  5.   ],
       [ 0.88 ,  0.   ,  2.6  , ...,  0.68 ,  9.8  ,  5.   ],
       [ 0.76 ,  0.04 ,  2.3  , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 0.51 ,  0.13 ,  2.3  , ...,  0.75 , 11.   ,  6.   ],
       [ 0.645,  0.12 ,  2.   , ...,  0.71 , 10.2  ,  5.   ],
       [ 0.31 ,  0.47 ,  3.6  , ...,  0.66 , 11.   ,  6.   ]])

In [36]:
classe

array([5, 5, 5, ..., 6, 5, 6])

In [38]:
previsores

ValueError: ignored

In [ ]:
from sklearn.model_selection import train_test_split

previsores_treinamento, previsoresteste, classe_treinamento, classe_teste =
train_test_split()_