<a href="https://colab.research.google.com/github/itimes-digital/Bootcamp-Analista-de-Machine-Learning-IGTI/blob/master/desafio_modulo_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('winequality-red.csv', sep=';')
dataset.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [4]:
dataset.shape

(1599, 12)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
dataset.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [ ]:
dataset['residual sugar'].isnull().sum()

0

In [ ]:
dataset.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
dataset['residual sugar'].median()

2.2

In [ ]:
dataset[['fixed acidity', 'pH']].corr()

fixed acidity        pH
fixed acidity       1.000000 -0.682978
pH                 -0.682978  1.000000

In [ ]:
dataset[['quality', 'alcohol']].corr()

quality   alcohol
quality  1.000000  0.476166
alcohol  0.476166  1.000000

In [ ]:
dataset.query('quality == 5').count()

fixed acidity           681
volatile acidity        681
citric acid             681
residual sugar          681
chlorides               681
free sulfur dioxide     681
total sulfur dioxide    681
density                 681
pH                      681
sulphates               681
alcohol                 681
quality                 681
dtype: int64

In [6]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(dataset)
print(scaler)

MinMaxScaler(copy=True, feature_range=(0, 1))


In [ ]:
print(scaler.data_range_)

[1.130e+01 1.460e+00 1.000e+00 1.460e+01 5.990e-01 7.100e+01 2.830e+02
 1.362e-02 1.270e+00 1.670e+00 6.500e+00 1.000e+00]


In [ ]:
print(scaler.data_max_)

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       1.     ]


In [ ]:
print(scaler.data_min_)

[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     0.     ]


In [22]:
previsores = dataset.iloc[:, 0:11].values
classe = dataset.iloc[:, 11].values

In [23]:
previsores

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
classe

array([5, 5, 5, ..., 6, 5, 6])

In [24]:
scaler_prev = MinMaxScaler(feature_range=(-1,1))

previsores = scaler_prev.fit_transform(previsores)

In [25]:
previsores[0:1599]

array([[-0.50442478, -0.20547945, -1.        , ...,  0.21259843,
        -0.7245509 , -0.69230769],
       [-0.43362832,  0.04109589, -1.        , ..., -0.27559055,
        -0.58083832, -0.56923077],
       [-0.43362832, -0.12328767, -0.92      , ..., -0.18110236,
        -0.61676647, -0.56923077],
       ...,
       [-0.69911504, -0.46575342, -0.74      , ...,  0.07086614,
        -0.49700599, -0.2       ],
       [-0.7699115 , -0.28082192, -0.76      , ...,  0.30708661,
        -0.54491018, -0.44615385],
       [-0.75221239, -0.73972603, -0.06      , ...,  0.02362205,
        -0.60479042, -0.2       ]])

In [26]:
np.min(previsores[0:1599])

-1.0

In [27]:
previsores.shape

(1599, 11)

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, 
                                                                                              classe, 
                                                                                              random_state = 1,
                                                                                              test_size = 0.30)

In [29]:
previsores_treinamento

array([[-0.36283186,  0.65753425, -1.        , ...,  0.24409449,
        -0.80838323, -0.23076923],
       [-0.52212389, -0.49315068, -0.8       , ..., -0.11811024,
        -0.83233533, -0.35384615],
       [-0.27433628, -0.01369863, -1.        , ..., -0.16535433,
        -0.73652695, -0.6       ],
       ...,
       [-0.6460177 , -0.17123288, -0.82      , ..., -0.03937008,
        -0.80838323, -0.26153846],
       [-0.53982301, -0.30136986, -1.        , ..., -0.00787402,
        -0.7005988 , -0.81538462],
       [-0.20353982, -0.61643836,  0.        , ..., -0.25984252,
        -0.56886228,  0.26153846]])

Aplicando KNN

In [30]:
from sklearn.neighbors import KNeighborsClassifier

clf_KNN = KNeighborsClassifier(n_neighbors=5)

clf_KNN.fit(previsores_treinamento, classe_treinamento)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [31]:
previsoes = clf_KNN.predict(previsores_teste)

In [32]:
precisao = accuracy_score(classe_teste, previsoes)

In [33]:
precisao

0.5645833333333333

Aplicando Decision Tree

In [34]:
from sklearn.tree import DecisionTreeClassifier

clf_arvore = DecisionTreeClassifier()

clf_arvore.fit(previsores_treinamento, classe_treinamento)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [35]:
previsoes = clf_arvore.predict(previsores_teste)

In [36]:
precisao = accuracy_score(classe_teste, previsoes)

In [37]:
precisao

0.59375

Aplicando Random Forest

In [38]:
from sklearn.ensemble import RandomForestClassifier

clf_floresta = RandomForestClassifier(max_depth=10, random_state=1)

clf_floresta.fit(previsores_treinamento, classe_treinamento)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [39]:
previsoes = clf_floresta.predict(previsores_teste)

In [40]:
precisao = accuracy_score(classe_teste, previsoes)

In [41]:
precisao

0.6833333333333333

Aplicando SVM

In [42]:
from sklearn.svm import SVC

clf_svm = SVC(gamma='auto',kernel='rbf')

clf_svm.fit(previsores_treinamento, classe_treinamento)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [43]:
previsoes = clf_svm.predict(previsores_teste)

In [44]:
precisao = accuracy_score(classe_teste, previsoes)

In [45]:
precisao

0.5875

Aplicando Rede MLP

In [46]:
previsores_treinamento.shape

(1119, 11)

In [47]:
classe_treinamento.shape

(1119,)

In [48]:
from sklearn.neural_network import MLPClassifier

clf_mlp = MLPClassifier(alpha=1e5, 
                        hidden_layer_sizes=(5, 5), 
                        random_state=1)

In [49]:
clf_mlp.fit(previsores_treinamento, classe_treinamento)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=100000.0, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 5), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [50]:
previsoes = clf_mlp.predict(previsores_teste)

In [51]:
clf_mlp.score(previsores_teste, classe_teste)

0.40625

In [52]:
precisao = accuracy_score(classe_teste, previsoes)

In [53]:
precisao

0.40625

Aplicando Random Forest com LabelEnconder

In [54]:
dataset_label = dataset

In [55]:
dataset_label['quality'] = dataset_label['quality'].replace([6,7,8], 1) # vinho bom
dataset_label['quality'] = dataset_label['quality'].replace([3,4,5], 0) # vinho ruim

In [56]:
dataset_label.head(100)

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0             7.4             0.700         0.00  ...       0.56      9.4        0
1             7.8             0.880         0.00  ...       0.68      9.8        0
2             7.8             0.760         0.04  ...       0.65      9.8        0
3            11.2             0.280         0.56  ...       0.58      9.8        1
4             7.4             0.700         0.00  ...       0.56      9.4        0
..            ...               ...          ...  ...        ...      ...      ...
95            4.7             0.600         0.17  ...       0.60     12.9        1
96            6.8             0.775         0.00  ...       0.56     10.7        0
97            7.0             0.500         0.25  ...       0.63      9.2        0
98            7.6             0.900         0.06  ...       0.56      9.8        0
99            8.1             0.545         0.18  ...       0.59      9.0        1

[100 rows x 12 columns]

In [57]:
previsores = dataset.iloc[:, 0:11].values
classe = dataset.iloc[:, 11].values

In [58]:
scaler_prev = MinMaxScaler(feature_range=(-1,1))

previsores = scaler_prev.fit_transform(previsores)

In [59]:
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, 
                                                                                              classe, 
                                                                                              random_state = 1,
                                                                                              test_size = 0.30)

In [60]:
from sklearn.ensemble import RandomForestClassifier

clf_floresta = RandomForestClassifier(max_depth=10, random_state=1)

clf_floresta.fit(previsores_treinamento, classe_treinamento)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [61]:
previsoes = clf_floresta.predict(previsores_teste)

In [62]:
precisao = accuracy_score(classe_teste, previsoes)

In [63]:
precisao

0.80625